"""added course duration

Revision ID: 28147f5ff4de
Revises: 
Create Date: 2026-06-30 14:13:49.924738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28147f5ff4de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
